### ISSUE TITLE
Patch for CUDA 11

### ISSUE THREAD

**Issue by half-potato** [bartoszek/AUR-colmap#2]
In the latest version of CUDA, they have removed support for compute 3 and 3.5. This simple patch allows COLMAP to compile correctly after this update:
```
diff --git a/cmake/SelectCudaComputeArch.cmake b/cmake/SelectCudaComputeArch.cmake
index 00980ba..ce95d02 100644
--- a/cmake/SelectCudaComputeArch.cmake
+++ b/cmake/SelectCudaComputeArch.cmake
@@ -67,14 +67,14 @@ endif()
 list(APPEND CUDA_KNOWN_GPU_ARCHITECTURES "Kepler" "Maxwell")
 
 # This list will be used for CUDA_ARCH_NAME = Common option (enabled by default)
-set(CUDA_COMMON_GPU_ARCHITECTURES "3.0" "3.5" "5.0")
+set(CUDA_COMMON_GPU_ARCHITECTURES "5.0")
 
 if(CUDA_VERSION VERSION_LESS "7.0")
   set(CUDA_LIMIT_GPU_ARCHITECTURE "5.2")
 endif()
 
 # This list is used to filter CUDA archs when autodetecting
-set(CUDA_ALL_GPU_ARCHITECTURES "3.0" "3.2" "3.5" "5.0")
+set(CUDA_ALL_GPU_ARCHITECTURES "5.0")
 
 if(CUDA_VERSION VERSION_EQUAL "7.0" OR CUDA_VERSION VERSION_GREATER "7.0")
   list(APPEND CUDA_KNOWN_GPU_ARCHITECTURES "Kepler+Tegra" "Kepler+Tesla" "Maxwell+Tegra")
```

**Comment by bartoszek** [comment]
Good call, there's already a patch for `cuda11` in included upstream - will cherry-pick and push it to AUR 🤗 
https://github.com/colmap/colmap/commit/b7c03103fbdfc1c3a711332b911d0b4a855562ac

**Comment by bartoszek** [comment]
I've updated to `colmap:3.6` which already includes `cuda:11` patch.

> btw. if `colmap:cuda automatic arch detection` doesn't work for you - you can specify `cuda compute capability` with `_CUDA_ARCH` env var - e.g. `makepkg _CUDA_ARCH=5.2` 🤔
_[list of gpu compute capability](https://developer.nvidia.com/cuda-gpus#compute)_
