### ISSUE TITLE
AUR package build broken

### ISSUE THREAD

**Issue by Yugen42** [bartoszek/AUR-colmap#3]
I'm guessing there's a dependency that's missing.

FAILED: src/exe/colmap 
: && /usr/bin/c++ -march=native -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -Wno-maybe-uninitialized -fopenmp -Wall -std=c++17 -O3 -DNDEBUG -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now   -rdynamic src/exe/CMakeFiles/colmap_exe.dir/colmap.cc.o src/exe/CMakeFiles/colmap_exe.dir/database.cc.o src/exe/CMakeFiles/colmap_exe.dir/feature.cc.o src/exe/CMakeFiles/colmap_exe.dir/gui.cc.o src/exe/CMakeFiles/colmap_exe.dir/image.cc.o src/exe/CMakeFiles/colmap_exe.dir/model.cc.o src/exe/CMakeFiles/colmap_exe.dir/mvs.cc.o src/exe/CMakeFiles/colmap_exe.dir/sfm.cc.o src/exe/CMakeFiles/colmap_exe.dir/vocab_tree.cc.o -o src/exe/colmap  src/libcolmap.a  src/libcolmap_cuda.a  src/libcolmap.a  src/libcolmap_cuda.a  lib/FLANN/libflann.a  lib/Graclus/libgraclus.a  lib/LSD/liblsd.a  lib/PBA/libpba.a  lib/PoissonRecon/libpoisson_recon.a  lib/SQLite/libsqlite3.a  lib/SiftGPU/libsift_gpu.a  -lGLEW  lib/VLFeat/libvlfeat.a  /usr/lib/libboost_filesystem.a  /usr/lib/libboost_atomic.a  /usr/lib/libboost_program_options.a  /usr/lib/libboost_system.a  -lglog  -lfreeimage  /usr/lib/libceres.so.2.1.0  /usr/lib/libglog.so.0.6.0  /usr/lib/libgflags.so.2.2.2  -lpthread  -lOpenGL  -lGLX  -lGLU  /usr/lib/libQt5OpenGL.so.5.15.4  /usr/lib/libQt5Widgets.so.5.15.4  /usr/lib/libQt5Gui.so.5.15.4  /usr/lib/libQt5Core.so.5.15.4  -lgmpxx  -lmpfr  -lgmp  -lpthread  /opt/cuda/lib64/libcudart_static.a  -ldl  -Wl,-Bstatic  -lrt  -Wl,-Bdynamic && :
**/usr/bin/ld: warning: libglog.so.0, needed by /usr/lib/libceres.so.2.1.0, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /usr/lib/libceres.so.2.1.0: undefined reference to `google::InitVLOG3__(int**, int*, char const*, int)'**
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by bartoszek** [comment]
It's not `colmap` issue, your `ceres` package requires rebuilt after `glog` update. 
If I might suggest sometimes, install `rebuild-detector`, it will report witch AUR packages requires rebuilt after every sys upgrade.

**Comment by Yugen42** [comment]
Thanks, that helped.
